apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: logsources.metrifuge.io
  labels:
    app.kubernetes.io/name: metrifuge
    app.kubernetes.io/instance: metrifuge
    app.kubernetes.io/version: "v1"
    app.kubernetes.io/component: crd
    app.kubernetes.io/part-of: metrifuge
spec:
  group: metrifuge.io
  names:
    kind: LogSource
    listKind: LogSourceList
    plural: logsources
    singular: logsource
    shortNames:
      - ls
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - type
                - source
              properties:
                type:
                  type: string
                  description: Type of the log source
                  enum: [PodSource, PVCSource, LocalSource, CmdSource]
                source:
                  type: object
                  required:
                    - type
                  properties:
                    type:
                      type: string
                      description: Type of the source
                      enum: [PodSource, PVCSource, LocalSource, CmdSource]
                    logSource:
                      type: object
                      properties:
                        name:
                          type: string
                          description: Name of the log source
                    pvcSource:
                      type: object
                      properties:
                        pvc:
                          type: object
                          required:
                            - name
                          properties:
                            name:
                              type: string
                              description: Name of the PersistentVolumeClaim
                        logFilePath:
                          type: string
                          description: Path to the log file within the PVC
                    podSource:
                      type: object
                      properties:
                        pod:
                          type: object
                          required:
                            - name
                            - container
                          properties:
                            name:
                              type: string
                              description: Name of the Pod
                            container:
                              type: string
                              description: Name of the container within the Pod
                    localSource:
                      type: object
                      properties:
                        path:
                          type: string
                          description: Path to the local log file
                    cmdSource:
                      type: object
                      properties:
                        command:
                          type: string
                          description: Command to execute to get logs
      subresources:
        status: {}
  conversion:
    strategy: None
